,pipeline.0.normalize,pipeline.1.filter.gene,pipeline.2.filter.cell,pipeline.3.feature.cell,info,run_id
0,Log1P,FilterGenesRegression,FilterCellsPlaceHolder,WeightedFeaturePCA,"wandb: ERROR Run im5daiql errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 660, in __call__
wandb: ERROR     data.data.obsm[self.out] = filter_func(feat)
wandb: ERROR                                ^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 679, in _filter_enclasc
wandb: ERROR     feat_index = np.argpartition(scores, -num_genes)[-num_genes:]
wandb: ERROR                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/numpy/core/fromnumeric.py"", line 858, in argpartition
wandb: ERROR     return _wrapfunc(a, 'argpartition', kth, axis=axis, kind=kind, order=order)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/numpy/core/fromnumeric.py"", line 59, in _wrapfunc
wandb: ERROR     return bound(*args, **kwds)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^
wandb: ERROR ValueError: kth(=-1000) out of bounds (1000)",im5daiql
1,Log1P,FilterGenesRegression,FilterCellsPlaceHolder,WeightedFeatureSVD,"wandb: ERROR Run 3hmfkeyc errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 660, in __call__
wandb: ERROR     data.data.obsm[self.out] = filter_func(feat)
wandb: ERROR                                ^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 679, in _filter_enclasc
wandb: ERROR     feat_index = np.argpartition(scores, -num_genes)[-num_genes:]
wandb: ERROR                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/numpy/core/fromnumeric.py"", line 858, in argpartition
wandb: ERROR     return _wrapfunc(a, 'argpartition', kth, axis=axis, kind=kind, order=order)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/numpy/core/fromnumeric.py"", line 59, in _wrapfunc
wandb: ERROR     return bound(*args, **kwds)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^
wandb: ERROR ValueError: kth(=-1000) out of bounds (1000)",3hmfkeyc
2,Log1P,FilterGenesRegression,FilterCellsScanpyOrder,WeightedFeaturePCA,"wandb: ERROR Run fiuml5vc errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 660, in __call__
wandb: ERROR     data.data.obsm[self.out] = filter_func(feat)
wandb: ERROR                                ^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 679, in _filter_enclasc
wandb: ERROR     feat_index = np.argpartition(scores, -num_genes)[-num_genes:]
wandb: ERROR                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/numpy/core/fromnumeric.py"", line 858, in argpartition
wandb: ERROR     return _wrapfunc(a, 'argpartition', kth, axis=axis, kind=kind, order=order)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/numpy/core/fromnumeric.py"", line 59, in _wrapfunc
wandb: ERROR     return bound(*args, **kwds)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^
wandb: ERROR ValueError: kth(=-1000) out of bounds (1000)",fiuml5vc
3,Log1P,FilterGenesRegression,FilterCellsScanpyOrder,WeightedFeatureSVD,"wandb: ERROR Run tefdq1eg errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 660, in __call__
wandb: ERROR     data.data.obsm[self.out] = filter_func(feat)
wandb: ERROR                                ^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 679, in _filter_enclasc
wandb: ERROR     feat_index = np.argpartition(scores, -num_genes)[-num_genes:]
wandb: ERROR                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/numpy/core/fromnumeric.py"", line 858, in argpartition
wandb: ERROR     return _wrapfunc(a, 'argpartition', kth, axis=axis, kind=kind, order=order)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/numpy/core/fromnumeric.py"", line 59, in _wrapfunc
wandb: ERROR     return bound(*args, **kwds)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^
wandb: ERROR ValueError: kth(=-1000) out of bounds (1000)",tefdq1eg
4,Log1P,FilterGenesTopK,FilterCellsPlaceHolder,WeightedFeaturePCA,"wandb: ERROR Run ly7ipin9 errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 383, in __call__
wandb: ERROR     mask = self._get_preserve_mask(gene_summary)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 516, in _get_preserve_mask
wandb: ERROR     raise ValueError(f""{self.num_genes=!r} > total number of genes: {total_num_genes}"")
wandb: ERROR ValueError: self.num_genes=1000 > total number of genes: 1000",ly7ipin9
5,Log1P,FilterGenesTopK,FilterCellsPlaceHolder,WeightedFeatureSVD,"wandb: ERROR Run joz0lowa errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 383, in __call__
wandb: ERROR     mask = self._get_preserve_mask(gene_summary)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 516, in _get_preserve_mask
wandb: ERROR     raise ValueError(f""{self.num_genes=!r} > total number of genes: {total_num_genes}"")
wandb: ERROR ValueError: self.num_genes=1000 > total number of genes: 1000",joz0lowa
6,Log1P,FilterGenesTopK,FilterCellsScanpyOrder,WeightedFeaturePCA,"wandb: ERROR Run 3ug7mhwr errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 383, in __call__
wandb: ERROR     mask = self._get_preserve_mask(gene_summary)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 516, in _get_preserve_mask
wandb: ERROR     raise ValueError(f""{self.num_genes=!r} > total number of genes: {total_num_genes}"")
wandb: ERROR ValueError: self.num_genes=1000 > total number of genes: 1000",3ug7mhwr
7,Log1P,FilterGenesTopK,FilterCellsScanpyOrder,WeightedFeatureSVD,"wandb: ERROR Run lrck62fs errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 383, in __call__
wandb: ERROR     mask = self._get_preserve_mask(gene_summary)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 516, in _get_preserve_mask
wandb: ERROR     raise ValueError(f""{self.num_genes=!r} > total number of genes: {total_num_genes}"")
wandb: ERROR ValueError: self.num_genes=1000 > total number of genes: 1000",lrck62fs
8,Log1P,HighlyVariableGenesLogarithmizedByMeanAndDisp,FilterCellsScanpyOrder,WeightedFeaturePCA,"wandb: ERROR Run wolzjkez errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/cell_feature.py"", line 50, in __call__
wandb: ERROR     gene_feat = gene_pca.fit_transform(feat.T)  # decompose into gene features
wandb: ERROR                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/utils/_set_output.py"", line 157, in wrapped
wandb: ERROR     data_to_wrap = f(self, X, *args, **kwargs)
wandb: ERROR                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/base.py"", line 1152, in wrapper
wandb: ERROR     return fit_method(estimator, *args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/decomposition/_pca.py"", line 460, in fit_transform
wandb: ERROR     U, S, Vt = self._fit(X)
wandb: ERROR                ^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/decomposition/_pca.py"", line 483, in _fit
wandb: ERROR     X = self._validate_data(
wandb: ERROR         ^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/base.py"", line 605, in _validate_data
wandb: ERROR     out = check_array(X, input_name=""X"", **check_params)
wandb: ERROR           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/utils/validation.py"", line 976, in check_array
wandb: ERROR     raise ValueError(
wandb: ERROR ValueError: Found array with 0 feature(s) (shape=(158, 0)) while a minimum of 1 is required by PCA.",wolzjkez
9,Log1P,HighlyVariableGenesLogarithmizedByMeanAndDisp,FilterCellsScanpyOrder,WeightedFeatureSVD,"wandb: ERROR Run 49prfixk errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/cell_feature.py"", line 98, in __call__
wandb: ERROR     svd.fit_transform(feat)
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/utils/_set_output.py"", line 157, in wrapped
wandb: ERROR     data_to_wrap = f(self, X, *args, **kwargs)
wandb: ERROR                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/base.py"", line 1145, in wrapper
wandb: ERROR     estimator._validate_params()
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/base.py"", line 638, in _validate_params
wandb: ERROR     validate_parameter_constraints(
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/utils/_param_validation.py"", line 96, in validate_parameter_constraints
wandb: ERROR     raise InvalidParameterError(
wandb: ERROR sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of TruncatedSVD must be an int in the range [1, inf). Got -1 instead.",49prfixk
10,NormalizePlaceHolder,FilterGenesRegression,FilterCellsPlaceHolder,WeightedFeaturePCA,"wandb: ERROR Run hf963xnv errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 660, in __call__
wandb: ERROR     data.data.obsm[self.out] = filter_func(feat)
wandb: ERROR                                ^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 679, in _filter_enclasc
wandb: ERROR     feat_index = np.argpartition(scores, -num_genes)[-num_genes:]
wandb: ERROR                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/numpy/core/fromnumeric.py"", line 858, in argpartition
wandb: ERROR     return _wrapfunc(a, 'argpartition', kth, axis=axis, kind=kind, order=order)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/numpy/core/fromnumeric.py"", line 59, in _wrapfunc
wandb: ERROR     return bound(*args, **kwds)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^
wandb: ERROR ValueError: kth(=-1000) out of bounds (1000)",hf963xnv
11,NormalizePlaceHolder,FilterGenesRegression,FilterCellsPlaceHolder,WeightedFeatureSVD,"wandb: ERROR Run 3ww67lh2 errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 660, in __call__
wandb: ERROR     data.data.obsm[self.out] = filter_func(feat)
wandb: ERROR                                ^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 679, in _filter_enclasc
wandb: ERROR     feat_index = np.argpartition(scores, -num_genes)[-num_genes:]
wandb: ERROR                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/numpy/core/fromnumeric.py"", line 858, in argpartition
wandb: ERROR     return _wrapfunc(a, 'argpartition', kth, axis=axis, kind=kind, order=order)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/numpy/core/fromnumeric.py"", line 59, in _wrapfunc
wandb: ERROR     return bound(*args, **kwds)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^
wandb: ERROR ValueError: kth(=-1000) out of bounds (1000)",3ww67lh2
12,NormalizePlaceHolder,FilterGenesRegression,FilterCellsScanpyOrder,WeightedFeaturePCA,"wandb: ERROR Run hnhrktb7 errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 660, in __call__
wandb: ERROR     data.data.obsm[self.out] = filter_func(feat)
wandb: ERROR                                ^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 679, in _filter_enclasc
wandb: ERROR     feat_index = np.argpartition(scores, -num_genes)[-num_genes:]
wandb: ERROR                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/numpy/core/fromnumeric.py"", line 858, in argpartition
wandb: ERROR     return _wrapfunc(a, 'argpartition', kth, axis=axis, kind=kind, order=order)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/numpy/core/fromnumeric.py"", line 59, in _wrapfunc
wandb: ERROR     return bound(*args, **kwds)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^
wandb: ERROR ValueError: kth(=-1000) out of bounds (1000)",hnhrktb7
13,NormalizePlaceHolder,FilterGenesRegression,FilterCellsScanpyOrder,WeightedFeatureSVD,"wandb: ERROR Run zb5uzosa errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 660, in __call__
wandb: ERROR     data.data.obsm[self.out] = filter_func(feat)
wandb: ERROR                                ^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 679, in _filter_enclasc
wandb: ERROR     feat_index = np.argpartition(scores, -num_genes)[-num_genes:]
wandb: ERROR                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/numpy/core/fromnumeric.py"", line 858, in argpartition
wandb: ERROR     return _wrapfunc(a, 'argpartition', kth, axis=axis, kind=kind, order=order)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/numpy/core/fromnumeric.py"", line 59, in _wrapfunc
wandb: ERROR     return bound(*args, **kwds)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^
wandb: ERROR ValueError: kth(=-1000) out of bounds (1000)",zb5uzosa
14,NormalizePlaceHolder,FilterGenesTopK,FilterCellsPlaceHolder,WeightedFeaturePCA,"wandb: ERROR Run cnbuojuc errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 383, in __call__
wandb: ERROR     mask = self._get_preserve_mask(gene_summary)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 516, in _get_preserve_mask
wandb: ERROR     raise ValueError(f""{self.num_genes=!r} > total number of genes: {total_num_genes}"")
wandb: ERROR ValueError: self.num_genes=1000 > total number of genes: 1000",cnbuojuc
15,NormalizePlaceHolder,FilterGenesTopK,FilterCellsPlaceHolder,WeightedFeatureSVD,"wandb: ERROR Run pp1wmcx8 errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 383, in __call__
wandb: ERROR     mask = self._get_preserve_mask(gene_summary)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 516, in _get_preserve_mask
wandb: ERROR     raise ValueError(f""{self.num_genes=!r} > total number of genes: {total_num_genes}"")
wandb: ERROR ValueError: self.num_genes=1000 > total number of genes: 1000",pp1wmcx8
16,NormalizePlaceHolder,FilterGenesTopK,FilterCellsScanpyOrder,WeightedFeaturePCA,"wandb: ERROR Run 6iboqusc errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 383, in __call__
wandb: ERROR     mask = self._get_preserve_mask(gene_summary)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 516, in _get_preserve_mask
wandb: ERROR     raise ValueError(f""{self.num_genes=!r} > total number of genes: {total_num_genes}"")
wandb: ERROR ValueError: self.num_genes=1000 > total number of genes: 1000",6iboqusc
17,NormalizePlaceHolder,FilterGenesTopK,FilterCellsScanpyOrder,WeightedFeatureSVD,"wandb: ERROR Run nu1rzfuh errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 383, in __call__
wandb: ERROR     mask = self._get_preserve_mask(gene_summary)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 516, in _get_preserve_mask
wandb: ERROR     raise ValueError(f""{self.num_genes=!r} > total number of genes: {total_num_genes}"")
wandb: ERROR ValueError: self.num_genes=1000 > total number of genes: 1000",nu1rzfuh
18,NormalizePlaceHolder,HighlyVariableGenesLogarithmizedByMeanAndDisp,FilterCellsPlaceHolder,WeightedFeaturePCA,"wandb: ERROR Run 5efx7i1s errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/interface.py"", line 68, in __call__
wandb: ERROR     self.func(data.data, **self.func_kwargs)
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/scanpy/preprocessing/_highly_variable_genes.py"", line 453, in highly_variable_genes
wandb: ERROR     df = _highly_variable_genes_single_batch(
wandb: ERROR          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/scanpy/preprocessing/_highly_variable_genes.py"", line 225, in _highly_variable_genes_single_batch
wandb: ERROR     df[""mean_bin""] = pd.cut(df[""means""], bins=n_bins)
wandb: ERROR                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/pandas/core/reshape/tile.py"", line 263, in cut
wandb: ERROR     raise ValueError(
wandb: ERROR ValueError: cannot specify integer `bins` when input data contains infinity",5efx7i1s
19,NormalizePlaceHolder,HighlyVariableGenesLogarithmizedByMeanAndDisp,FilterCellsPlaceHolder,WeightedFeatureSVD,"wandb: ERROR Run ypcmihtd errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/interface.py"", line 68, in __call__
wandb: ERROR     self.func(data.data, **self.func_kwargs)
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/scanpy/preprocessing/_highly_variable_genes.py"", line 453, in highly_variable_genes
wandb: ERROR     df = _highly_variable_genes_single_batch(
wandb: ERROR          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/scanpy/preprocessing/_highly_variable_genes.py"", line 225, in _highly_variable_genes_single_batch
wandb: ERROR     df[""mean_bin""] = pd.cut(df[""means""], bins=n_bins)
wandb: ERROR                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/pandas/core/reshape/tile.py"", line 263, in cut
wandb: ERROR     raise ValueError(
wandb: ERROR ValueError: cannot specify integer `bins` when input data contains infinity",ypcmihtd
20,NormalizePlaceHolder,HighlyVariableGenesLogarithmizedByMeanAndDisp,FilterCellsScanpyOrder,WeightedFeaturePCA,"wandb: ERROR Run no7p3d0x errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/interface.py"", line 68, in __call__
wandb: ERROR     self.func(data.data, **self.func_kwargs)
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/scanpy/preprocessing/_highly_variable_genes.py"", line 453, in highly_variable_genes
wandb: ERROR     df = _highly_variable_genes_single_batch(
wandb: ERROR          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/scanpy/preprocessing/_highly_variable_genes.py"", line 225, in _highly_variable_genes_single_batch
wandb: ERROR     df[""mean_bin""] = pd.cut(df[""means""], bins=n_bins)
wandb: ERROR                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/pandas/core/reshape/tile.py"", line 263, in cut
wandb: ERROR     raise ValueError(
wandb: ERROR ValueError: cannot specify integer `bins` when input data contains infinity",no7p3d0x
21,NormalizePlaceHolder,HighlyVariableGenesLogarithmizedByMeanAndDisp,FilterCellsScanpyOrder,WeightedFeatureSVD,"wandb: ERROR Run 26rdbj9s errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/interface.py"", line 68, in __call__
wandb: ERROR     self.func(data.data, **self.func_kwargs)
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/scanpy/preprocessing/_highly_variable_genes.py"", line 453, in highly_variable_genes
wandb: ERROR     df = _highly_variable_genes_single_batch(
wandb: ERROR          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/scanpy/preprocessing/_highly_variable_genes.py"", line 225, in _highly_variable_genes_single_batch
wandb: ERROR     df[""mean_bin""] = pd.cut(df[""means""], bins=n_bins)
wandb: ERROR                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/pandas/core/reshape/tile.py"", line 263, in cut
wandb: ERROR     raise ValueError(
wandb: ERROR ValueError: cannot specify integer `bins` when input data contains infinity",26rdbj9s
22,NormalizePlaceHolder,HighlyVariableGenesLogarithmizedByTopGenes,FilterCellsPlaceHolder,WeightedFeaturePCA,"wandb: ERROR Run 2dq71p17 errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/interface.py"", line 68, in __call__
wandb: ERROR     self.func(data.data, **self.func_kwargs)
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/scanpy/preprocessing/_highly_variable_genes.py"", line 453, in highly_variable_genes
wandb: ERROR     df = _highly_variable_genes_single_batch(
wandb: ERROR          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/scanpy/preprocessing/_highly_variable_genes.py"", line 225, in _highly_variable_genes_single_batch
wandb: ERROR     df[""mean_bin""] = pd.cut(df[""means""], bins=n_bins)
wandb: ERROR                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/pandas/core/reshape/tile.py"", line 263, in cut
wandb: ERROR     raise ValueError(
wandb: ERROR ValueError: cannot specify integer `bins` when input data contains infinity",2dq71p17
23,NormalizePlaceHolder,HighlyVariableGenesLogarithmizedByTopGenes,FilterCellsPlaceHolder,WeightedFeatureSVD,"wandb: ERROR Run yc1uczup errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/interface.py"", line 68, in __call__
wandb: ERROR     self.func(data.data, **self.func_kwargs)
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/scanpy/preprocessing/_highly_variable_genes.py"", line 453, in highly_variable_genes
wandb: ERROR     df = _highly_variable_genes_single_batch(
wandb: ERROR          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/scanpy/preprocessing/_highly_variable_genes.py"", line 225, in _highly_variable_genes_single_batch
wandb: ERROR     df[""mean_bin""] = pd.cut(df[""means""], bins=n_bins)
wandb: ERROR                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/pandas/core/reshape/tile.py"", line 263, in cut
wandb: ERROR     raise ValueError(
wandb: ERROR ValueError: cannot specify integer `bins` when input data contains infinity",yc1uczup
24,NormalizePlaceHolder,HighlyVariableGenesLogarithmizedByTopGenes,FilterCellsScanpyOrder,WeightedFeaturePCA,"wandb: ERROR Run gxkt1mb4 errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/interface.py"", line 68, in __call__
wandb: ERROR     self.func(data.data, **self.func_kwargs)
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/scanpy/preprocessing/_highly_variable_genes.py"", line 453, in highly_variable_genes
wandb: ERROR     df = _highly_variable_genes_single_batch(
wandb: ERROR          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/scanpy/preprocessing/_highly_variable_genes.py"", line 225, in _highly_variable_genes_single_batch
wandb: ERROR     df[""mean_bin""] = pd.cut(df[""means""], bins=n_bins)
wandb: ERROR                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/pandas/core/reshape/tile.py"", line 263, in cut
wandb: ERROR     raise ValueError(
wandb: ERROR ValueError: cannot specify integer `bins` when input data contains infinity",gxkt1mb4
25,NormalizePlaceHolder,HighlyVariableGenesLogarithmizedByTopGenes,FilterCellsScanpyOrder,WeightedFeatureSVD,"wandb: ERROR Run w4pq9cvv errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/interface.py"", line 68, in __call__
wandb: ERROR     self.func(data.data, **self.func_kwargs)
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/scanpy/preprocessing/_highly_variable_genes.py"", line 453, in highly_variable_genes
wandb: ERROR     df = _highly_variable_genes_single_batch(
wandb: ERROR          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/scanpy/preprocessing/_highly_variable_genes.py"", line 225, in _highly_variable_genes_single_batch
wandb: ERROR     df[""mean_bin""] = pd.cut(df[""means""], bins=n_bins)
wandb: ERROR                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/pandas/core/reshape/tile.py"", line 263, in cut
wandb: ERROR     raise ValueError(
wandb: ERROR ValueError: cannot specify integer `bins` when input data contains infinity",w4pq9cvv
26,NormalizeTotal,FilterGenesRegression,FilterCellsPlaceHolder,WeightedFeaturePCA,"wandb: ERROR Run aprqczf8 errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 660, in __call__
wandb: ERROR     data.data.obsm[self.out] = filter_func(feat)
wandb: ERROR                                ^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 679, in _filter_enclasc
wandb: ERROR     feat_index = np.argpartition(scores, -num_genes)[-num_genes:]
wandb: ERROR                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/numpy/core/fromnumeric.py"", line 858, in argpartition
wandb: ERROR     return _wrapfunc(a, 'argpartition', kth, axis=axis, kind=kind, order=order)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/numpy/core/fromnumeric.py"", line 59, in _wrapfunc
wandb: ERROR     return bound(*args, **kwds)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^
wandb: ERROR ValueError: kth(=-1000) out of bounds (1000)",aprqczf8
27,NormalizeTotal,FilterGenesRegression,FilterCellsPlaceHolder,WeightedFeatureSVD,"wandb: ERROR Run luo7r0ke errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 660, in __call__
wandb: ERROR     data.data.obsm[self.out] = filter_func(feat)
wandb: ERROR                                ^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 679, in _filter_enclasc
wandb: ERROR     feat_index = np.argpartition(scores, -num_genes)[-num_genes:]
wandb: ERROR                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/numpy/core/fromnumeric.py"", line 858, in argpartition
wandb: ERROR     return _wrapfunc(a, 'argpartition', kth, axis=axis, kind=kind, order=order)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/numpy/core/fromnumeric.py"", line 59, in _wrapfunc
wandb: ERROR     return bound(*args, **kwds)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^
wandb: ERROR ValueError: kth(=-1000) out of bounds (1000)",luo7r0ke
28,NormalizeTotal,FilterGenesRegression,FilterCellsScanpyOrder,WeightedFeaturePCA,"wandb: ERROR Run 0e07wpnt errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 660, in __call__
wandb: ERROR     data.data.obsm[self.out] = filter_func(feat)
wandb: ERROR                                ^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 679, in _filter_enclasc
wandb: ERROR     feat_index = np.argpartition(scores, -num_genes)[-num_genes:]
wandb: ERROR                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/numpy/core/fromnumeric.py"", line 858, in argpartition
wandb: ERROR     return _wrapfunc(a, 'argpartition', kth, axis=axis, kind=kind, order=order)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/numpy/core/fromnumeric.py"", line 59, in _wrapfunc
wandb: ERROR     return bound(*args, **kwds)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^
wandb: ERROR ValueError: kth(=-1000) out of bounds (1000)",0e07wpnt
29,NormalizeTotal,FilterGenesRegression,FilterCellsScanpyOrder,WeightedFeatureSVD,"wandb: ERROR Run uwgiam37 errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 660, in __call__
wandb: ERROR     data.data.obsm[self.out] = filter_func(feat)
wandb: ERROR                                ^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 679, in _filter_enclasc
wandb: ERROR     feat_index = np.argpartition(scores, -num_genes)[-num_genes:]
wandb: ERROR                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/numpy/core/fromnumeric.py"", line 858, in argpartition
wandb: ERROR     return _wrapfunc(a, 'argpartition', kth, axis=axis, kind=kind, order=order)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/numpy/core/fromnumeric.py"", line 59, in _wrapfunc
wandb: ERROR     return bound(*args, **kwds)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^
wandb: ERROR ValueError: kth(=-1000) out of bounds (1000)",uwgiam37
30,NormalizeTotal,FilterGenesTopK,FilterCellsPlaceHolder,WeightedFeaturePCA,"wandb: ERROR Run qamptwja errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 383, in __call__
wandb: ERROR     mask = self._get_preserve_mask(gene_summary)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 516, in _get_preserve_mask
wandb: ERROR     raise ValueError(f""{self.num_genes=!r} > total number of genes: {total_num_genes}"")
wandb: ERROR ValueError: self.num_genes=1000 > total number of genes: 1000",qamptwja
31,NormalizeTotal,FilterGenesTopK,FilterCellsPlaceHolder,WeightedFeatureSVD,"wandb: ERROR Run dm2ioms3 errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 383, in __call__
wandb: ERROR     mask = self._get_preserve_mask(gene_summary)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 516, in _get_preserve_mask
wandb: ERROR     raise ValueError(f""{self.num_genes=!r} > total number of genes: {total_num_genes}"")
wandb: ERROR ValueError: self.num_genes=1000 > total number of genes: 1000",dm2ioms3
32,NormalizeTotal,FilterGenesTopK,FilterCellsScanpyOrder,WeightedFeaturePCA,"wandb: ERROR Run 1yg6ai5w errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 383, in __call__
wandb: ERROR     mask = self._get_preserve_mask(gene_summary)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 516, in _get_preserve_mask
wandb: ERROR     raise ValueError(f""{self.num_genes=!r} > total number of genes: {total_num_genes}"")
wandb: ERROR ValueError: self.num_genes=1000 > total number of genes: 1000",1yg6ai5w
33,NormalizeTotal,FilterGenesTopK,FilterCellsScanpyOrder,WeightedFeatureSVD,"wandb: ERROR Run afltljh6 errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 383, in __call__
wandb: ERROR     mask = self._get_preserve_mask(gene_summary)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 516, in _get_preserve_mask
wandb: ERROR     raise ValueError(f""{self.num_genes=!r} > total number of genes: {total_num_genes}"")
wandb: ERROR ValueError: self.num_genes=1000 > total number of genes: 1000",afltljh6
34,NormalizeTotal,HighlyVariableGenesLogarithmizedByMeanAndDisp,FilterCellsPlaceHolder,WeightedFeaturePCA,"wandb: ERROR Run jp7vsor6 errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/interface.py"", line 68, in __call__
wandb: ERROR     self.func(data.data, **self.func_kwargs)
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/scanpy/preprocessing/_highly_variable_genes.py"", line 453, in highly_variable_genes
wandb: ERROR     df = _highly_variable_genes_single_batch(
wandb: ERROR          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/scanpy/preprocessing/_highly_variable_genes.py"", line 225, in _highly_variable_genes_single_batch
wandb: ERROR     df[""mean_bin""] = pd.cut(df[""means""], bins=n_bins)
wandb: ERROR                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/pandas/core/reshape/tile.py"", line 263, in cut
wandb: ERROR     raise ValueError(
wandb: ERROR ValueError: cannot specify integer `bins` when input data contains infinity",jp7vsor6
35,NormalizeTotal,HighlyVariableGenesLogarithmizedByMeanAndDisp,FilterCellsPlaceHolder,WeightedFeatureSVD,"wandb: ERROR Run 3qnwc8m1 errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/interface.py"", line 68, in __call__
wandb: ERROR     self.func(data.data, **self.func_kwargs)
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/scanpy/preprocessing/_highly_variable_genes.py"", line 453, in highly_variable_genes
wandb: ERROR     df = _highly_variable_genes_single_batch(
wandb: ERROR          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/scanpy/preprocessing/_highly_variable_genes.py"", line 225, in _highly_variable_genes_single_batch
wandb: ERROR     df[""mean_bin""] = pd.cut(df[""means""], bins=n_bins)
wandb: ERROR                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/pandas/core/reshape/tile.py"", line 263, in cut
wandb: ERROR     raise ValueError(
wandb: ERROR ValueError: cannot specify integer `bins` when input data contains infinity",3qnwc8m1
36,NormalizeTotal,HighlyVariableGenesLogarithmizedByMeanAndDisp,FilterCellsScanpyOrder,WeightedFeaturePCA,"wandb: ERROR Run 6ib89fjn errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/interface.py"", line 68, in __call__
wandb: ERROR     self.func(data.data, **self.func_kwargs)
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/scanpy/preprocessing/_highly_variable_genes.py"", line 453, in highly_variable_genes
wandb: ERROR     df = _highly_variable_genes_single_batch(
wandb: ERROR          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/scanpy/preprocessing/_highly_variable_genes.py"", line 225, in _highly_variable_genes_single_batch
wandb: ERROR     df[""mean_bin""] = pd.cut(df[""means""], bins=n_bins)
wandb: ERROR                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/pandas/core/reshape/tile.py"", line 263, in cut
wandb: ERROR     raise ValueError(
wandb: ERROR ValueError: cannot specify integer `bins` when input data contains infinity",6ib89fjn
37,NormalizeTotal,HighlyVariableGenesLogarithmizedByMeanAndDisp,FilterCellsScanpyOrder,WeightedFeatureSVD,"wandb: ERROR Run f724fggm errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/interface.py"", line 68, in __call__
wandb: ERROR     self.func(data.data, **self.func_kwargs)
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/scanpy/preprocessing/_highly_variable_genes.py"", line 453, in highly_variable_genes
wandb: ERROR     df = _highly_variable_genes_single_batch(
wandb: ERROR          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/scanpy/preprocessing/_highly_variable_genes.py"", line 225, in _highly_variable_genes_single_batch
wandb: ERROR     df[""mean_bin""] = pd.cut(df[""means""], bins=n_bins)
wandb: ERROR                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/pandas/core/reshape/tile.py"", line 263, in cut
wandb: ERROR     raise ValueError(
wandb: ERROR ValueError: cannot specify integer `bins` when input data contains infinity",f724fggm
38,NormalizeTotal,HighlyVariableGenesLogarithmizedByTopGenes,FilterCellsPlaceHolder,WeightedFeaturePCA,"wandb: ERROR Run iuuegybd errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/interface.py"", line 68, in __call__
wandb: ERROR     self.func(data.data, **self.func_kwargs)
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/scanpy/preprocessing/_highly_variable_genes.py"", line 453, in highly_variable_genes
wandb: ERROR     df = _highly_variable_genes_single_batch(
wandb: ERROR          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/scanpy/preprocessing/_highly_variable_genes.py"", line 225, in _highly_variable_genes_single_batch
wandb: ERROR     df[""mean_bin""] = pd.cut(df[""means""], bins=n_bins)
wandb: ERROR                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/pandas/core/reshape/tile.py"", line 263, in cut
wandb: ERROR     raise ValueError(
wandb: ERROR ValueError: cannot specify integer `bins` when input data contains infinity",iuuegybd
39,NormalizeTotal,HighlyVariableGenesLogarithmizedByTopGenes,FilterCellsPlaceHolder,WeightedFeatureSVD,"wandb: ERROR Run kyyhjuqx errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/interface.py"", line 68, in __call__
wandb: ERROR     self.func(data.data, **self.func_kwargs)
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/scanpy/preprocessing/_highly_variable_genes.py"", line 453, in highly_variable_genes
wandb: ERROR     df = _highly_variable_genes_single_batch(
wandb: ERROR          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/scanpy/preprocessing/_highly_variable_genes.py"", line 225, in _highly_variable_genes_single_batch
wandb: ERROR     df[""mean_bin""] = pd.cut(df[""means""], bins=n_bins)
wandb: ERROR                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/pandas/core/reshape/tile.py"", line 263, in cut
wandb: ERROR     raise ValueError(
wandb: ERROR ValueError: cannot specify integer `bins` when input data contains infinity",kyyhjuqx
40,NormalizeTotal,HighlyVariableGenesLogarithmizedByTopGenes,FilterCellsScanpyOrder,WeightedFeaturePCA,"wandb: ERROR Run gto8fzx0 errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/interface.py"", line 68, in __call__
wandb: ERROR     self.func(data.data, **self.func_kwargs)
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/scanpy/preprocessing/_highly_variable_genes.py"", line 453, in highly_variable_genes
wandb: ERROR     df = _highly_variable_genes_single_batch(
wandb: ERROR          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/scanpy/preprocessing/_highly_variable_genes.py"", line 225, in _highly_variable_genes_single_batch
wandb: ERROR     df[""mean_bin""] = pd.cut(df[""means""], bins=n_bins)
wandb: ERROR                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/pandas/core/reshape/tile.py"", line 263, in cut
wandb: ERROR     raise ValueError(
wandb: ERROR ValueError: cannot specify integer `bins` when input data contains infinity",gto8fzx0
41,NormalizeTotal,HighlyVariableGenesLogarithmizedByTopGenes,FilterCellsScanpyOrder,WeightedFeatureSVD,"wandb: ERROR Run slt36f8r errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/interface.py"", line 68, in __call__
wandb: ERROR     self.func(data.data, **self.func_kwargs)
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/scanpy/preprocessing/_highly_variable_genes.py"", line 453, in highly_variable_genes
wandb: ERROR     df = _highly_variable_genes_single_batch(
wandb: ERROR          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/scanpy/preprocessing/_highly_variable_genes.py"", line 225, in _highly_variable_genes_single_batch
wandb: ERROR     df[""mean_bin""] = pd.cut(df[""means""], bins=n_bins)
wandb: ERROR                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/pandas/core/reshape/tile.py"", line 263, in cut
wandb: ERROR     raise ValueError(
wandb: ERROR ValueError: cannot specify integer `bins` when input data contains infinity",slt36f8r
42,ScTransform,FilterGenesRegression,FilterCellsPlaceHolder,WeightedFeaturePCA,"wandb: ERROR Run y8uwv2yz errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 660, in __call__
wandb: ERROR     data.data.obsm[self.out] = filter_func(feat)
wandb: ERROR                                ^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 679, in _filter_enclasc
wandb: ERROR     feat_index = np.argpartition(scores, -num_genes)[-num_genes:]
wandb: ERROR                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/numpy/core/fromnumeric.py"", line 858, in argpartition
wandb: ERROR     return _wrapfunc(a, 'argpartition', kth, axis=axis, kind=kind, order=order)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/numpy/core/fromnumeric.py"", line 59, in _wrapfunc
wandb: ERROR     return bound(*args, **kwds)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^
wandb: ERROR ValueError: kth(=-1000) out of bounds (1000)",y8uwv2yz
43,ScTransform,FilterGenesRegression,FilterCellsPlaceHolder,WeightedFeatureSVD,"wandb: ERROR Run 3fg1ns9y errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 660, in __call__
wandb: ERROR     data.data.obsm[self.out] = filter_func(feat)
wandb: ERROR                                ^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 679, in _filter_enclasc
wandb: ERROR     feat_index = np.argpartition(scores, -num_genes)[-num_genes:]
wandb: ERROR                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/numpy/core/fromnumeric.py"", line 858, in argpartition
wandb: ERROR     return _wrapfunc(a, 'argpartition', kth, axis=axis, kind=kind, order=order)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/numpy/core/fromnumeric.py"", line 59, in _wrapfunc
wandb: ERROR     return bound(*args, **kwds)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^
wandb: ERROR ValueError: kth(=-1000) out of bounds (1000)",3fg1ns9y
44,ScTransform,FilterGenesRegression,FilterCellsScanpyOrder,WeightedFeaturePCA,"wandb: ERROR Run 8230xkb9 errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 660, in __call__
wandb: ERROR     data.data.obsm[self.out] = filter_func(feat)
wandb: ERROR                                ^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 679, in _filter_enclasc
wandb: ERROR     feat_index = np.argpartition(scores, -num_genes)[-num_genes:]
wandb: ERROR                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/numpy/core/fromnumeric.py"", line 858, in argpartition
wandb: ERROR     return _wrapfunc(a, 'argpartition', kth, axis=axis, kind=kind, order=order)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/numpy/core/fromnumeric.py"", line 59, in _wrapfunc
wandb: ERROR     return bound(*args, **kwds)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^
wandb: ERROR ValueError: kth(=-1000) out of bounds (1000)",8230xkb9
45,ScTransform,FilterGenesRegression,FilterCellsScanpyOrder,WeightedFeatureSVD,"wandb: ERROR Run sk0r3sk2 errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 660, in __call__
wandb: ERROR     data.data.obsm[self.out] = filter_func(feat)
wandb: ERROR                                ^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 679, in _filter_enclasc
wandb: ERROR     feat_index = np.argpartition(scores, -num_genes)[-num_genes:]
wandb: ERROR                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/numpy/core/fromnumeric.py"", line 858, in argpartition
wandb: ERROR     return _wrapfunc(a, 'argpartition', kth, axis=axis, kind=kind, order=order)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/numpy/core/fromnumeric.py"", line 59, in _wrapfunc
wandb: ERROR     return bound(*args, **kwds)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^
wandb: ERROR ValueError: kth(=-1000) out of bounds (1000)",sk0r3sk2
46,ScTransform,FilterGenesTopK,FilterCellsPlaceHolder,WeightedFeaturePCA,"wandb: ERROR Run gc93srg7 errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 383, in __call__
wandb: ERROR     mask = self._get_preserve_mask(gene_summary)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 516, in _get_preserve_mask
wandb: ERROR     raise ValueError(f""{self.num_genes=!r} > total number of genes: {total_num_genes}"")
wandb: ERROR ValueError: self.num_genes=1000 > total number of genes: 1000",gc93srg7
47,ScTransform,FilterGenesTopK,FilterCellsPlaceHolder,WeightedFeatureSVD,"wandb: ERROR Run 29ox464m errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 383, in __call__
wandb: ERROR     mask = self._get_preserve_mask(gene_summary)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 516, in _get_preserve_mask
wandb: ERROR     raise ValueError(f""{self.num_genes=!r} > total number of genes: {total_num_genes}"")
wandb: ERROR ValueError: self.num_genes=1000 > total number of genes: 1000",29ox464m
48,ScTransform,FilterGenesTopK,FilterCellsScanpyOrder,WeightedFeaturePCA,"wandb: ERROR Run 3uxi365y errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 383, in __call__
wandb: ERROR     mask = self._get_preserve_mask(gene_summary)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 516, in _get_preserve_mask
wandb: ERROR     raise ValueError(f""{self.num_genes=!r} > total number of genes: {total_num_genes}"")
wandb: ERROR ValueError: self.num_genes=1000 > total number of genes: 1000",3uxi365y
49,ScTransform,FilterGenesTopK,FilterCellsScanpyOrder,WeightedFeatureSVD,"wandb: ERROR Run viyuynnu errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 383, in __call__
wandb: ERROR     mask = self._get_preserve_mask(gene_summary)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 516, in _get_preserve_mask
wandb: ERROR     raise ValueError(f""{self.num_genes=!r} > total number of genes: {total_num_genes}"")
wandb: ERROR ValueError: self.num_genes=1000 > total number of genes: 1000",viyuynnu
50,ScTransform,HighlyVariableGenesLogarithmizedByMeanAndDisp,FilterCellsScanpyOrder,WeightedFeaturePCA,"wandb: ERROR Run hsvabi5e errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/cell_feature.py"", line 50, in __call__
wandb: ERROR     gene_feat = gene_pca.fit_transform(feat.T)  # decompose into gene features
wandb: ERROR                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/utils/_set_output.py"", line 157, in wrapped
wandb: ERROR     data_to_wrap = f(self, X, *args, **kwargs)
wandb: ERROR                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/base.py"", line 1152, in wrapper
wandb: ERROR     return fit_method(estimator, *args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/decomposition/_pca.py"", line 460, in fit_transform
wandb: ERROR     U, S, Vt = self._fit(X)
wandb: ERROR                ^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/decomposition/_pca.py"", line 483, in _fit
wandb: ERROR     X = self._validate_data(
wandb: ERROR         ^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/base.py"", line 605, in _validate_data
wandb: ERROR     out = check_array(X, input_name=""X"", **check_params)
wandb: ERROR           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/utils/validation.py"", line 976, in check_array
wandb: ERROR     raise ValueError(
wandb: ERROR ValueError: Found array with 0 feature(s) (shape=(245, 0)) while a minimum of 1 is required by PCA.",hsvabi5e
51,ScTransform,HighlyVariableGenesLogarithmizedByMeanAndDisp,FilterCellsScanpyOrder,WeightedFeatureSVD,"wandb: ERROR Run qr5ligaq errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/cell_feature.py"", line 98, in __call__
wandb: ERROR     svd.fit_transform(feat)
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/utils/_set_output.py"", line 157, in wrapped
wandb: ERROR     data_to_wrap = f(self, X, *args, **kwargs)
wandb: ERROR                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/base.py"", line 1145, in wrapper
wandb: ERROR     estimator._validate_params()
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/base.py"", line 638, in _validate_params
wandb: ERROR     validate_parameter_constraints(
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/utils/_param_validation.py"", line 96, in validate_parameter_constraints
wandb: ERROR     raise InvalidParameterError(
wandb: ERROR sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of TruncatedSVD must be an int in the range [1, inf). Got -1 instead.",qr5ligaq
52,ScaleFeature,FilterGenesPercentile,FilterCellsScanpyOrder,WeightedFeaturePCA,"wandb: ERROR Run 799eui2m errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/cell_feature.py"", line 50, in __call__
wandb: ERROR     gene_feat = gene_pca.fit_transform(feat.T)  # decompose into gene features
wandb: ERROR                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/utils/_set_output.py"", line 157, in wrapped
wandb: ERROR     data_to_wrap = f(self, X, *args, **kwargs)
wandb: ERROR                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/base.py"", line 1152, in wrapper
wandb: ERROR     return fit_method(estimator, *args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/decomposition/_pca.py"", line 460, in fit_transform
wandb: ERROR     U, S, Vt = self._fit(X)
wandb: ERROR                ^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/decomposition/_pca.py"", line 483, in _fit
wandb: ERROR     X = self._validate_data(
wandb: ERROR         ^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/base.py"", line 605, in _validate_data
wandb: ERROR     out = check_array(X, input_name=""X"", **check_params)
wandb: ERROR           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/utils/validation.py"", line 976, in check_array
wandb: ERROR     raise ValueError(
wandb: ERROR ValueError: Found array with 0 feature(s) (shape=(981, 0)) while a minimum of 1 is required by PCA.",799eui2m
53,ScaleFeature,FilterGenesPercentile,FilterCellsScanpyOrder,WeightedFeatureSVD,"wandb: ERROR Run dwjnatv4 errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/cell_feature.py"", line 98, in __call__
wandb: ERROR     svd.fit_transform(feat)
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/utils/_set_output.py"", line 157, in wrapped
wandb: ERROR     data_to_wrap = f(self, X, *args, **kwargs)
wandb: ERROR                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/base.py"", line 1145, in wrapper
wandb: ERROR     estimator._validate_params()
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/base.py"", line 638, in _validate_params
wandb: ERROR     validate_parameter_constraints(
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/utils/_param_validation.py"", line 96, in validate_parameter_constraints
wandb: ERROR     raise InvalidParameterError(
wandb: ERROR sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of TruncatedSVD must be an int in the range [1, inf). Got -1 instead.",dwjnatv4
54,ScaleFeature,FilterGenesPlaceHolder,FilterCellsScanpyOrder,WeightedFeaturePCA,"wandb: ERROR Run ddnix2dl errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/cell_feature.py"", line 50, in __call__
wandb: ERROR     gene_feat = gene_pca.fit_transform(feat.T)  # decompose into gene features
wandb: ERROR                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/utils/_set_output.py"", line 157, in wrapped
wandb: ERROR     data_to_wrap = f(self, X, *args, **kwargs)
wandb: ERROR                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/base.py"", line 1152, in wrapper
wandb: ERROR     return fit_method(estimator, *args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/decomposition/_pca.py"", line 460, in fit_transform
wandb: ERROR     U, S, Vt = self._fit(X)
wandb: ERROR                ^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/decomposition/_pca.py"", line 483, in _fit
wandb: ERROR     X = self._validate_data(
wandb: ERROR         ^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/base.py"", line 605, in _validate_data
wandb: ERROR     out = check_array(X, input_name=""X"", **check_params)
wandb: ERROR           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/utils/validation.py"", line 976, in check_array
wandb: ERROR     raise ValueError(
wandb: ERROR ValueError: Found array with 0 feature(s) (shape=(1000, 0)) while a minimum of 1 is required by PCA.",ddnix2dl
55,ScaleFeature,FilterGenesPlaceHolder,FilterCellsScanpyOrder,WeightedFeatureSVD,"wandb: ERROR Run g4egxzq5 errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/cell_feature.py"", line 98, in __call__
wandb: ERROR     svd.fit_transform(feat)
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/utils/_set_output.py"", line 157, in wrapped
wandb: ERROR     data_to_wrap = f(self, X, *args, **kwargs)
wandb: ERROR                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/base.py"", line 1145, in wrapper
wandb: ERROR     estimator._validate_params()
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/base.py"", line 638, in _validate_params
wandb: ERROR     validate_parameter_constraints(
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/utils/_param_validation.py"", line 96, in validate_parameter_constraints
wandb: ERROR     raise InvalidParameterError(
wandb: ERROR sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of TruncatedSVD must be an int in the range [1, inf). Got -1 instead.",g4egxzq5
56,ScaleFeature,FilterGenesRegression,FilterCellsPlaceHolder,WeightedFeaturePCA,"wandb: ERROR Run qbss49do errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 660, in __call__
wandb: ERROR     data.data.obsm[self.out] = filter_func(feat)
wandb: ERROR                                ^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 679, in _filter_enclasc
wandb: ERROR     feat_index = np.argpartition(scores, -num_genes)[-num_genes:]
wandb: ERROR                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/numpy/core/fromnumeric.py"", line 858, in argpartition
wandb: ERROR     return _wrapfunc(a, 'argpartition', kth, axis=axis, kind=kind, order=order)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/numpy/core/fromnumeric.py"", line 59, in _wrapfunc
wandb: ERROR     return bound(*args, **kwds)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^
wandb: ERROR ValueError: kth(=-1000) out of bounds (1000)",qbss49do
57,ScaleFeature,FilterGenesRegression,FilterCellsPlaceHolder,WeightedFeatureSVD,"wandb: ERROR Run kuwwgho7 errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 660, in __call__
wandb: ERROR     data.data.obsm[self.out] = filter_func(feat)
wandb: ERROR                                ^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 679, in _filter_enclasc
wandb: ERROR     feat_index = np.argpartition(scores, -num_genes)[-num_genes:]
wandb: ERROR                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/numpy/core/fromnumeric.py"", line 858, in argpartition
wandb: ERROR     return _wrapfunc(a, 'argpartition', kth, axis=axis, kind=kind, order=order)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/numpy/core/fromnumeric.py"", line 59, in _wrapfunc
wandb: ERROR     return bound(*args, **kwds)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^
wandb: ERROR ValueError: kth(=-1000) out of bounds (1000)",kuwwgho7
58,ScaleFeature,FilterGenesRegression,FilterCellsScanpyOrder,WeightedFeaturePCA,"wandb: ERROR Run z2b7sp8b errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 660, in __call__
wandb: ERROR     data.data.obsm[self.out] = filter_func(feat)
wandb: ERROR                                ^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 679, in _filter_enclasc
wandb: ERROR     feat_index = np.argpartition(scores, -num_genes)[-num_genes:]
wandb: ERROR                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/numpy/core/fromnumeric.py"", line 858, in argpartition
wandb: ERROR     return _wrapfunc(a, 'argpartition', kth, axis=axis, kind=kind, order=order)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/numpy/core/fromnumeric.py"", line 59, in _wrapfunc
wandb: ERROR     return bound(*args, **kwds)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^
wandb: ERROR ValueError: kth(=-1000) out of bounds (1000)",z2b7sp8b
59,ScaleFeature,FilterGenesRegression,FilterCellsScanpyOrder,WeightedFeatureSVD,"wandb: ERROR Run mrxhmqs8 errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 660, in __call__
wandb: ERROR     data.data.obsm[self.out] = filter_func(feat)
wandb: ERROR                                ^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 679, in _filter_enclasc
wandb: ERROR     feat_index = np.argpartition(scores, -num_genes)[-num_genes:]
wandb: ERROR                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/numpy/core/fromnumeric.py"", line 858, in argpartition
wandb: ERROR     return _wrapfunc(a, 'argpartition', kth, axis=axis, kind=kind, order=order)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/numpy/core/fromnumeric.py"", line 59, in _wrapfunc
wandb: ERROR     return bound(*args, **kwds)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^
wandb: ERROR ValueError: kth(=-1000) out of bounds (1000)",mrxhmqs8
60,ScaleFeature,FilterGenesScanpyOrder,FilterCellsPlaceHolder,WeightedFeaturePCA,"wandb: ERROR Run ndpgmwkj errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/cell_feature.py"", line 50, in __call__
wandb: ERROR     gene_feat = gene_pca.fit_transform(feat.T)  # decompose into gene features
wandb: ERROR                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/utils/_set_output.py"", line 157, in wrapped
wandb: ERROR     data_to_wrap = f(self, X, *args, **kwargs)
wandb: ERROR                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/base.py"", line 1152, in wrapper
wandb: ERROR     return fit_method(estimator, *args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/decomposition/_pca.py"", line 460, in fit_transform
wandb: ERROR     U, S, Vt = self._fit(X)
wandb: ERROR                ^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/decomposition/_pca.py"", line 483, in _fit
wandb: ERROR     X = self._validate_data(
wandb: ERROR         ^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/base.py"", line 605, in _validate_data
wandb: ERROR     out = check_array(X, input_name=""X"", **check_params)
wandb: ERROR           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/utils/validation.py"", line 967, in check_array
wandb: ERROR     raise ValueError(
wandb: ERROR ValueError: Found array with 0 sample(s) (shape=(0, 8218)) while a minimum of 1 is required by PCA.",ndpgmwkj
61,ScaleFeature,FilterGenesScanpyOrder,FilterCellsPlaceHolder,WeightedFeatureSVD,"wandb: ERROR Run ims46lgr errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/cell_feature.py"", line 98, in __call__
wandb: ERROR     svd.fit_transform(feat)
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/utils/_set_output.py"", line 157, in wrapped
wandb: ERROR     data_to_wrap = f(self, X, *args, **kwargs)
wandb: ERROR                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/base.py"", line 1145, in wrapper
wandb: ERROR     estimator._validate_params()
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/base.py"", line 638, in _validate_params
wandb: ERROR     validate_parameter_constraints(
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/utils/_param_validation.py"", line 96, in validate_parameter_constraints
wandb: ERROR     raise InvalidParameterError(
wandb: ERROR sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of TruncatedSVD must be an int in the range [1, inf). Got -1 instead.",ims46lgr
62,ScaleFeature,FilterGenesScanpyOrder,FilterCellsScanpyOrder,WeightedFeaturePCA,"wandb: ERROR Run rhrunyyh errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/cell_feature.py"", line 50, in __call__
wandb: ERROR     gene_feat = gene_pca.fit_transform(feat.T)  # decompose into gene features
wandb: ERROR                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/utils/_set_output.py"", line 157, in wrapped
wandb: ERROR     data_to_wrap = f(self, X, *args, **kwargs)
wandb: ERROR                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/base.py"", line 1152, in wrapper
wandb: ERROR     return fit_method(estimator, *args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/decomposition/_pca.py"", line 460, in fit_transform
wandb: ERROR     U, S, Vt = self._fit(X)
wandb: ERROR                ^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/decomposition/_pca.py"", line 483, in _fit
wandb: ERROR     X = self._validate_data(
wandb: ERROR         ^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/base.py"", line 605, in _validate_data
wandb: ERROR     out = check_array(X, input_name=""X"", **check_params)
wandb: ERROR           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/utils/validation.py"", line 967, in check_array
wandb: ERROR     raise ValueError(
wandb: ERROR ValueError: Found array with 0 sample(s) (shape=(0, 0)) while a minimum of 1 is required by PCA.",rhrunyyh
63,ScaleFeature,FilterGenesScanpyOrder,FilterCellsScanpyOrder,WeightedFeatureSVD,"wandb: ERROR Run mk5rbswi errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/cell_feature.py"", line 98, in __call__
wandb: ERROR     svd.fit_transform(feat)
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/utils/_set_output.py"", line 157, in wrapped
wandb: ERROR     data_to_wrap = f(self, X, *args, **kwargs)
wandb: ERROR                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/base.py"", line 1145, in wrapper
wandb: ERROR     estimator._validate_params()
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/base.py"", line 638, in _validate_params
wandb: ERROR     validate_parameter_constraints(
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/utils/_param_validation.py"", line 96, in validate_parameter_constraints
wandb: ERROR     raise InvalidParameterError(
wandb: ERROR sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of TruncatedSVD must be an int in the range [1, inf). Got -1 instead.",mk5rbswi
64,ScaleFeature,FilterGenesTopK,FilterCellsPlaceHolder,WeightedFeaturePCA,"wandb: ERROR Run vhp8sgpz errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 383, in __call__
wandb: ERROR     mask = self._get_preserve_mask(gene_summary)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 516, in _get_preserve_mask
wandb: ERROR     raise ValueError(f""{self.num_genes=!r} > total number of genes: {total_num_genes}"")
wandb: ERROR ValueError: self.num_genes=1000 > total number of genes: 1000",vhp8sgpz
65,ScaleFeature,FilterGenesTopK,FilterCellsPlaceHolder,WeightedFeatureSVD,"wandb: ERROR Run 63f8kw5h errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 383, in __call__
wandb: ERROR     mask = self._get_preserve_mask(gene_summary)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 516, in _get_preserve_mask
wandb: ERROR     raise ValueError(f""{self.num_genes=!r} > total number of genes: {total_num_genes}"")
wandb: ERROR ValueError: self.num_genes=1000 > total number of genes: 1000",63f8kw5h
66,ScaleFeature,FilterGenesTopK,FilterCellsScanpyOrder,WeightedFeaturePCA,"wandb: ERROR Run yc3klbrs errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 383, in __call__
wandb: ERROR     mask = self._get_preserve_mask(gene_summary)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 516, in _get_preserve_mask
wandb: ERROR     raise ValueError(f""{self.num_genes=!r} > total number of genes: {total_num_genes}"")
wandb: ERROR ValueError: self.num_genes=1000 > total number of genes: 1000",yc3klbrs
67,ScaleFeature,FilterGenesTopK,FilterCellsScanpyOrder,WeightedFeatureSVD,"wandb: ERROR Run 0ognb4be errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 383, in __call__
wandb: ERROR     mask = self._get_preserve_mask(gene_summary)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/filter.py"", line 516, in _get_preserve_mask
wandb: ERROR     raise ValueError(f""{self.num_genes=!r} > total number of genes: {total_num_genes}"")
wandb: ERROR ValueError: self.num_genes=1000 > total number of genes: 1000",0ognb4be
68,ScaleFeature,HighlyVariableGenesLogarithmizedByMeanAndDisp,FilterCellsPlaceHolder,WeightedFeaturePCA,"wandb: ERROR Run cgct3emq errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/cell_feature.py"", line 50, in __call__
wandb: ERROR     gene_feat = gene_pca.fit_transform(feat.T)  # decompose into gene features
wandb: ERROR                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/utils/_set_output.py"", line 157, in wrapped
wandb: ERROR     data_to_wrap = f(self, X, *args, **kwargs)
wandb: ERROR                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/base.py"", line 1152, in wrapper
wandb: ERROR     return fit_method(estimator, *args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/decomposition/_pca.py"", line 460, in fit_transform
wandb: ERROR     U, S, Vt = self._fit(X)
wandb: ERROR                ^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/decomposition/_pca.py"", line 483, in _fit
wandb: ERROR     X = self._validate_data(
wandb: ERROR         ^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/base.py"", line 605, in _validate_data
wandb: ERROR     out = check_array(X, input_name=""X"", **check_params)
wandb: ERROR           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/utils/validation.py"", line 967, in check_array
wandb: ERROR     raise ValueError(
wandb: ERROR ValueError: Found array with 0 sample(s) (shape=(0, 8218)) while a minimum of 1 is required by PCA.",cgct3emq
69,ScaleFeature,HighlyVariableGenesLogarithmizedByMeanAndDisp,FilterCellsPlaceHolder,WeightedFeatureSVD,"wandb: ERROR Run d75by40l errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/cell_feature.py"", line 98, in __call__
wandb: ERROR     svd.fit_transform(feat)
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/utils/_set_output.py"", line 157, in wrapped
wandb: ERROR     data_to_wrap = f(self, X, *args, **kwargs)
wandb: ERROR                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/base.py"", line 1145, in wrapper
wandb: ERROR     estimator._validate_params()
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/base.py"", line 638, in _validate_params
wandb: ERROR     validate_parameter_constraints(
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/utils/_param_validation.py"", line 96, in validate_parameter_constraints
wandb: ERROR     raise InvalidParameterError(
wandb: ERROR sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of TruncatedSVD must be an int in the range [1, inf). Got -1 instead.",d75by40l
70,ScaleFeature,HighlyVariableGenesLogarithmizedByMeanAndDisp,FilterCellsScanpyOrder,WeightedFeaturePCA,"wandb: ERROR Run d93bv357 errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/cell_feature.py"", line 50, in __call__
wandb: ERROR     gene_feat = gene_pca.fit_transform(feat.T)  # decompose into gene features
wandb: ERROR                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/utils/_set_output.py"", line 157, in wrapped
wandb: ERROR     data_to_wrap = f(self, X, *args, **kwargs)
wandb: ERROR                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/base.py"", line 1152, in wrapper
wandb: ERROR     return fit_method(estimator, *args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/decomposition/_pca.py"", line 460, in fit_transform
wandb: ERROR     U, S, Vt = self._fit(X)
wandb: ERROR                ^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/decomposition/_pca.py"", line 483, in _fit
wandb: ERROR     X = self._validate_data(
wandb: ERROR         ^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/base.py"", line 605, in _validate_data
wandb: ERROR     out = check_array(X, input_name=""X"", **check_params)
wandb: ERROR           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/utils/validation.py"", line 967, in check_array
wandb: ERROR     raise ValueError(
wandb: ERROR ValueError: Found array with 0 sample(s) (shape=(0, 0)) while a minimum of 1 is required by PCA.",d93bv357
71,ScaleFeature,HighlyVariableGenesLogarithmizedByMeanAndDisp,FilterCellsScanpyOrder,WeightedFeatureSVD,"wandb: ERROR Run z7ijsojs errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/cell_feature.py"", line 98, in __call__
wandb: ERROR     svd.fit_transform(feat)
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/utils/_set_output.py"", line 157, in wrapped
wandb: ERROR     data_to_wrap = f(self, X, *args, **kwargs)
wandb: ERROR                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/base.py"", line 1145, in wrapper
wandb: ERROR     estimator._validate_params()
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/base.py"", line 638, in _validate_params
wandb: ERROR     validate_parameter_constraints(
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/utils/_param_validation.py"", line 96, in validate_parameter_constraints
wandb: ERROR     raise InvalidParameterError(
wandb: ERROR sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of TruncatedSVD must be an int in the range [1, inf). Got -1 instead.",z7ijsojs
72,ScaleFeature,HighlyVariableGenesLogarithmizedByTopGenes,FilterCellsScanpyOrder,WeightedFeaturePCA,"wandb: ERROR Run vpzp6u3s errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/cell_feature.py"", line 50, in __call__
wandb: ERROR     gene_feat = gene_pca.fit_transform(feat.T)  # decompose into gene features
wandb: ERROR                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/utils/_set_output.py"", line 157, in wrapped
wandb: ERROR     data_to_wrap = f(self, X, *args, **kwargs)
wandb: ERROR                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/base.py"", line 1152, in wrapper
wandb: ERROR     return fit_method(estimator, *args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/decomposition/_pca.py"", line 460, in fit_transform
wandb: ERROR     U, S, Vt = self._fit(X)
wandb: ERROR                ^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/decomposition/_pca.py"", line 483, in _fit
wandb: ERROR     X = self._validate_data(
wandb: ERROR         ^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/base.py"", line 605, in _validate_data
wandb: ERROR     out = check_array(X, input_name=""X"", **check_params)
wandb: ERROR           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/utils/validation.py"", line 976, in check_array
wandb: ERROR     raise ValueError(
wandb: ERROR ValueError: Found array with 0 feature(s) (shape=(1000, 0)) while a minimum of 1 is required by PCA.",vpzp6u3s
73,ScaleFeature,HighlyVariableGenesLogarithmizedByTopGenes,FilterCellsScanpyOrder,WeightedFeatureSVD,"wandb: ERROR Run t6vvi7g1 errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/cell_feature.py"", line 98, in __call__
wandb: ERROR     svd.fit_transform(feat)
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/utils/_set_output.py"", line 157, in wrapped
wandb: ERROR     data_to_wrap = f(self, X, *args, **kwargs)
wandb: ERROR                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/base.py"", line 1145, in wrapper
wandb: ERROR     estimator._validate_params()
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/base.py"", line 638, in _validate_params
wandb: ERROR     validate_parameter_constraints(
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/utils/_param_validation.py"", line 96, in validate_parameter_constraints
wandb: ERROR     raise InvalidParameterError(
wandb: ERROR sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of TruncatedSVD must be an int in the range [1, inf). Got -1 instead.",t6vvi7g1
74,ScaleFeature,HighlyVariableGenesRawCount,FilterCellsScanpyOrder,WeightedFeaturePCA,"wandb: ERROR Run eyp910t4 errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/cell_feature.py"", line 50, in __call__
wandb: ERROR     gene_feat = gene_pca.fit_transform(feat.T)  # decompose into gene features
wandb: ERROR                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/utils/_set_output.py"", line 157, in wrapped
wandb: ERROR     data_to_wrap = f(self, X, *args, **kwargs)
wandb: ERROR                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/base.py"", line 1152, in wrapper
wandb: ERROR     return fit_method(estimator, *args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/decomposition/_pca.py"", line 460, in fit_transform
wandb: ERROR     U, S, Vt = self._fit(X)
wandb: ERROR                ^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/decomposition/_pca.py"", line 483, in _fit
wandb: ERROR     X = self._validate_data(
wandb: ERROR         ^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/base.py"", line 605, in _validate_data
wandb: ERROR     out = check_array(X, input_name=""X"", **check_params)
wandb: ERROR           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/utils/validation.py"", line 976, in check_array
wandb: ERROR     raise ValueError(
wandb: ERROR ValueError: Found array with 0 feature(s) (shape=(1000, 0)) while a minimum of 1 is required by PCA.",eyp910t4
75,ScaleFeature,HighlyVariableGenesRawCount,FilterCellsScanpyOrder,WeightedFeatureSVD,"wandb: ERROR Run nzx7nzsi errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/cell_feature.py"", line 98, in __call__
wandb: ERROR     svd.fit_transform(feat)
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/utils/_set_output.py"", line 157, in wrapped
wandb: ERROR     data_to_wrap = f(self, X, *args, **kwargs)
wandb: ERROR                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/base.py"", line 1145, in wrapper
wandb: ERROR     estimator._validate_params()
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/base.py"", line 638, in _validate_params
wandb: ERROR     validate_parameter_constraints(
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/utils/_param_validation.py"", line 96, in validate_parameter_constraints
wandb: ERROR     raise InvalidParameterError(
wandb: ERROR sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of TruncatedSVD must be an int in the range [1, inf). Got -1 instead.",nzx7nzsi
