,params.0.Log1P.base,params.1.FilterGenesScanpyOrder.max_cells,params.1.FilterGenesScanpyOrder.max_counts,params.1.FilterGenesScanpyOrder.min_cells,params.1.FilterGenesScanpyOrder.min_counts,params.1.FilterGenesScanpyOrder.order,params.2.FilterCellsScanpyOrder.max_counts,params.2.FilterCellsScanpyOrder.max_genes,params.2.FilterCellsScanpyOrder.min_counts,params.2.FilterCellsScanpyOrder.min_genes,params.2.FilterCellsScanpyOrder.order,params.3.WeightedFeaturePCA.feat_norm_mode,params.3.WeightedFeaturePCA.n_components,info,run_id
0,5.636306559619132,0.9821377476722366,76857,0.033930150857467485,84,"['max_cells', 'min_counts', 'max_counts', 'min_cells']",31255,0.9568661130887288,712,0.034770897097474496,"['min_genes', 'max_genes', 'min_counts', 'max_counts']",standardize,0.942067711929648,"wandb: ERROR Run exm4hqnr errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 88, in evaluate_pipeline
wandb: ERROR     score = model.score(None, y)
wandb: ERROR             ^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/modules/base.py"", line 51, in score
wandb: ERROR     y_pred = self.predict(x)
wandb: ERROR              ^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/modules/single_modality/clustering/graphsc.py"", line 265, in predict
wandb: ERROR     pred = run_leiden(self.z)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/modules/single_modality/clustering/graphsc.py"", line 581, in run_leiden
wandb: ERROR     sc.tl.leiden(adata)
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/scanpy/tools/_leiden.py"", line 129, in leiden
wandb: ERROR     g = _utils.get_igraph_from_adjacency(adjacency, directed=directed)
wandb: ERROR         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/scanpy/_utils/__init__.py"", line 218, in get_igraph_from_adjacency
wandb: ERROR     g.es['weight'] = weights
wandb: ERROR     ~~~~^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/scipy/sparse/_base.py"", line 340, in __len__
wandb: ERROR     raise TypeError(""sparse array length is ambiguous; use getnnz()""
wandb: ERROR TypeError: sparse array length is ambiguous; use getnnz() or shape[0]",exm4hqnr
1,7.349416472749791,0.9636743824847156,65634,0.04709331645226237,3,"['max_counts', 'min_cells', 'max_cells', 'min_counts']",56226,0.9749059727564658,935,0.021359747481628857,"['min_counts', 'max_genes', 'min_genes', 'max_counts']",normalize,0.9229540161141656,"wandb: ERROR Run jq2ysd84 errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/wandb/agents/pyagent.py"", line 308, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File ""/home/zyxing/dance/examples/tuning/cluster_graphsc/main.py"", line 70, in evaluate_pipeline
wandb: ERROR     preprocessing_pipeline(data)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 232, in bounded_functional
wandb: ERROR     a(*args, **kwargs)
wandb: ERROR   File ""/home/zyxing/dance/dance/pipeline.py"", line 114, in __call__
wandb: ERROR     return self.functional(*args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/dance/dance/transforms/cell_feature.py"", line 50, in __call__
wandb: ERROR     gene_feat = gene_pca.fit_transform(feat.T)  # decompose into gene features
wandb: ERROR                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/utils/_set_output.py"", line 157, in wrapped
wandb: ERROR     data_to_wrap = f(self, X, *args, **kwargs)
wandb: ERROR                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/base.py"", line 1152, in wrapper
wandb: ERROR     return fit_method(estimator, *args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/decomposition/_pca.py"", line 460, in fit_transform
wandb: ERROR     U, S, Vt = self._fit(X)
wandb: ERROR                ^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/decomposition/_pca.py"", line 483, in _fit
wandb: ERROR     X = self._validate_data(
wandb: ERROR         ^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/base.py"", line 605, in _validate_data
wandb: ERROR     out = check_array(X, input_name=""X"", **check_params)
wandb: ERROR           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File ""/home/zyxing/anaconda3/envs/dance-env/lib/python3.11/site-packages/sklearn/utils/validation.py"", line 976, in check_array
wandb: ERROR     raise ValueError(
wandb: ERROR ValueError: Found array with 0 feature(s) (shape=(890, 0)) while a minimum of 1 is required by PCA.",jq2ysd84
